name: "\U0001F41B Bug report: webui"
description: "WebUI 功能运行不正常 / 失效"
title: "[BUG:WebUI] "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        提交前请确保已查阅文档并搜索过现有 Issues。

  - type: checkboxes
    id: issue-check
    attributes:
      label: 确认
      options:
        - label: 我已确认之前没有 Issue 涉及此 BUG，且当前使用的是最新代码
          required: true

  - type: textarea
    id: system-info
    attributes:
      label: 运行环境
      description: 请提供 Forge 版本、系统信息及浏览器版本。
      placeholder: |
        - Commit/Tag: 
        - OS: 
        - Python / PyTorch: 
        - Browser (Chrome/Edge/etc): 
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: BUG 描述与复现
      description: 请描述发生了什么以及复现步骤。**强烈建议直接在此处粘贴截图**。
      placeholder: |
        操作步骤：
        1. 打开...
        2. 点击...
        
        现象描述：
        按钮无反应 / 界面排版错误...
        
        (请在此处拖入截图)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 报错日志
      description: 请粘贴后台终端的报错信息，或浏览器控制台 (F12 -> Console) 的红色错误信息。
      render: shell