from .chattts import ChatTTSDownloader
from .cosyvoice1_base import CosyVoiceInstructDownloader
from .cosyvoice1_instruct import CosyVoiceInstructDownloader
from .cosyvoice2 import CosyVoice2Downloader
from .f5_tts import F5TTSDownloader
from .f5_tts_v1 import F5TTSV1Downloader
from .facebook_w2v_bert_2 import W2vBert2Downloader
from .faster_whisper_v3_turbo import FasterWhisperV3TDownloader
from .faster_whisper import FasterWhisperDownloader
from .fire_red_tts import FireRedTTSDownloader
from .fish_speech_1_2sft import FishSpeechDownloader
from .fish_speech_1_4 import FishSpeech14Downloader
from .fsmn_vad import FsmnVADDownloader
from .funasr_campplus import FunasrCampplusDownloader
from .gpt_sovits_v4 import GptSoVitsV4Downloader
from .index_tts import IndexTTSDownloader
from .index_tts_1_5 import IndexTTS15Downloader
from .index_tts_2 import IndexTTSV2Downloader
from .MaskGCT_semantic_codec import MaskGCTSemanticDownloader
from .nvidia_bigvgan_v2 import NvidiaBigvganV2Downloader
from .open_voice import OpenVoiceDownloader
from .resemble_enhance import ResembleEnhanceDownloader
from .sensevoice_small import SenseVoiceSmallDownloader
from .spark_tts import SparkTTSDownloader
from .vocos_mel_24khz import VocosMel24khzDownloader
